experiment_name: "2D Optimal"

blueprint_json: "latest_baseline_centroids.json"
rfs_weights: "rfs_weights.json"

path:
  root_dir: "/kaggle/working/organellenet" 
  jsons: ""
  dataset: "/kaggle/working/data"
  train_crops_json: "train_crops.json"
  val_crops_json: "val_crops.json"
  test_crops_json: "test_crops.json"
  checkpoint_dir: "checkpoints"

data:
  patch_dim: 256
  samples: 64000
  batch_size: 64
  num_workers: 4

model:
  spatial_dims: 2
  in_channels: 1
  out_channels: 13
  channels: [64, 128, 256, 512, 1024]
  strides: [2, 2, 2, 2]

training:
  num_epochs: 25
  learning_rate: 0.0001
  weight_decay: 0.0001
  warmup_epochs: 5
  mixed_precision: true
  early_stopping_patience: 10
  print_freq: 50
  entropy_masking: false

