experiment_name: "2D Optimal"

path:
  root_dir: "/kaggle/input/" 
  blueprint_json: ""   
  RFS_weights: ""   
  train_crops_json: "train_crops.json"
  val_crops_json: "val_crops.json"
  test_crops_json: "test_crops.json"
  checkpoint_dir: "checkpoints"

data:
  patch_dim: 256
  samples: 64000
  batch_size: 64
  num_workers: 4

model:
  spatial_dims: 2
  in_channels: 1
  out_channels: 13
  channels: [64, 128, 256, 512, 1024]
  strides: [2, 2, 2, 2]

training:
  num_epochs: 60
  learning_rate: 0.0001
  weight_decay: 0.0001
  warmup_epochs: 5
  mixed_precision: true

semantic_map:
  0: [35, 1]                                           # Background
  1: [50, 3, 4, 5]                                     # Mitochondria
  2: [8, 9]                                            # Vesicles
  3: [10, 11]                                          # Endosomes
  4: [12, 13]                                          # Lysosomes
  5: [44, 14, 15]                                      # Lipid Droplets
  6: [37, 20, 21, 26, 24, 25, 27, 28, 29]              # Nucleus
  7: [22, 23]                                          # Nuclear Pores
  8: [30, 36]                                          # Microtubules
  9: [49, 47, 48]                                      # Peroxisomes
  10: [6, 7]                                           # Golgi Apparatus
  11: [16, 17, 64]                                     # Endoplasmic Reticulum
  12: [18, 19]                                         # ER Exit Sites


architectures:
  unet: 2
  swin: 1
  resnet: 3